version: "3.9"

services:
  db:
    image: postgres:15
    container_name: cashier_db
    restart: always
    environment:
      POSTGRES_DB: cashier
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: ghcr.io/fedal-nl/cashier_backend_api:latest
    container_name: cashier_backend
    command: >
      sh -c "
      uv run python manage.py makemigrations &&
      uv run python manage.py migrate &&
      uv run python manage.py collectstatic --noinput &&
      uv run python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - backend_venv:/app/.venv
    env_file: 
      - .env
    depends_on:
      - db

  frontend:
    # image: ghcr.io/fedal-nl/cashier_frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: cashier_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    #ports:
    #  - "3000:5173"
    command: sh -c "npm install && npm run dev -- --host"
    stdin_open: true
    tty: true
    env_file:
      - .env

  website:
    build:
      context: ./aklahlana-website
      dockerfile: Dockerfile.dev
    container_name: aklahlana_website
    volumes:
      - ./aklahlana-website:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host"
    stdin_open: true
    tty: true
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    container_name: cashier_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static
    depends_on:
      - backend
      - frontend
      - website

volumes:
  postgres_data:
  static_volume:
  backend_venv: