server {
    listen 80;

    location /static/ {
        alias /static/;
    }

    location /api/ {
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /admin/ {
        proxy_pass http://backend:8000/admin/;
    }

    # location / {
    #     proxy_pass http://website:3001/;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    # }

    location / {
       proxy_pass http://frontend:3000/;
       proxy_set_header Host $host;
       proxy_set_header X-Real-IP $remote_addr;
    }

}
